
public enum Section {
	JUVENILE_FICTION,
	JUVENILE_NON_FICTION,
	JUVENILE_PICTURE,
	JUVENILE_DVD,
	JUVENILE_CD,
	FICTION,
	NON_FICTION,
	HIGH_SCHOOL_FICTION,
	HIGH_SCHOOL_NON_FICTION,
	YOUNG_PERSON_FICTION,
	YOUNG_PERSON_NON_FICTION,
	DVD,
	CD,
	PERIODICAL,
	SPANISH_NON_FICTION,
	SPANISH_FICTION
}
